      - name: Compile Kernel Image
        run: |
          CLANG_DIR=$GITHUB_WORKSPACE/toolchain/clang/bin
          GCC64_DIR=$GITHUB_WORKSPACE/toolchain/gcc64/bin
          GCC32_DIR=$GITHUB_WORKSPACE/toolchain/gcc32/bin
          
          export PATH=$CLANG_DIR:$GCC64_DIR:$GCC32_DIR:$PATH
          DTC_SYS=$(which dtc)
          
          BUILD_OPTIONS=(
            ARCH=arm64
            SUBARCH=arm64
            CC=clang
            CLANG_TRIPLE=aarch64-linux-gnu-
            CROSS_COMPILE=aarch64-linux-android-
            CROSS_COMPILE_ARM32=arm-linux-androideabi-
            REAL_CC=$CLANG_DIR/clang
            DTC=$DTC_SYS
          )
          
          # 1. Carrega o defconfig exato extraído do Moto G8 (rav)
          make "${BUILD_OPTIONS[@]}" rav_defconfig
          
          # 2. Compila a imagem compactada do kernel
          make "${BUILD_OPTIONS[@]}" -j$(nproc --all) Image.gz
