subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/msm_vb2
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/camera
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci

obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSMB_CAMERA) += laser_led/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
